name: Build MysteryMaze

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Windows
        run: g++ MysteryMaze.cpp -o MysteryMaze.exe
      - uses: actions/upload-artifact@v4
        with:
          name: MysteryMaze-Windows
          path: MysteryMaze.exe

  release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: MysteryMaze-Windows/MysteryMaze.exe
